BEGIN TRANSACTION;
CREATE TABLE mpmc_book ("id" integer NOT NULL PRIMARY KEY , "title" varchar(200) NOT NULL, "author" varchar(200) NOT NULL, "language" VARCHAR(20) NULL, "genre" varchar(30),  "summary" text NOT NULL);
INSERT INTO mpmc_book VALUES(15,'Della Patagonia e altri sogni. Viaggiatore con l''arte della pesca a mosca','Alvaro,Masseini','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(16,'La roccia condivisa','Mauro,Raspini','Italiano','Storytelling','Pescare nel buio più assoluto, ripetere i gesti rituali del lancio a memoria, affidarsi solo al tatto e all’udito. Lanciare nel buio è far volteggiare nell’aria la propria esperienza, il proprio passato di anni trascorsi sui fiumi. Nel buio la mosca è l’estensione della tua mente. Il passato ed i ricordi sono indispensabili per pescare nel buio e . . . per vivere la propria vita.”In frasi come questa è condensato il filo conduttore di questo lavoro, la passione per la pesca con la mosca e la ricerca della sua essenza alla scoperta dell’essenza del vivere.');
INSERT INTO mpmc_book VALUES(17,'Il pescatore all''amo in acque dolci','F.,Angeli','Italiano','Fishing','Il libro Il pescatore all''amo in acque dolci (manuale) è del 1954 scritto da F. Angeli, A. Renzi , tratta l''argomento pesca ed è edito da Casa Editrice Dott. CYA. E'' composto da 284 pagine.');
INSERT INTO mpmc_book VALUES(19,'Manuale della pesca a mosca ...','Carlo Cotta,Ramusino','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(20,'Manuale della pesca a mosca ...','Carlo Cotta,Ramusino','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(21,'Manuale della pesca a mosca ...','Carlo Cotta,Ramusino','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(22,'Manuale della pesca a mosca ...','Carlo Cotta,Ramusino','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(23,'Manuale della pesca a mosca ...','Carlo Cotta,Ramusino','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(24,'Pesca a mosca. Tecniche di lancio e pesca con la mosca artificiale. Pesci, attrezzatura','Luciano,Tosi','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(25,'Inseguendo il sole. Appunti di viaggio dalle terre dei salmoni','Alvaro,Masseini','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(26,'Il libro pratico del pescatore all''amo in acque dolci','Angelo,Bruni','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(27,'Le mie mosche. Come costruirle e impiegarle','Mario,Riccardi','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(28,'Scritto di sera','Léonce de,Boisset','Italiano','Storytelling','Sottotitolato "Le chiacchiere di un vecchio pescatore di trote", quest''opera offre al lettore il sottile piacere di una scrittura straordinaria.È suddiviso in quattro parti di una cinquantina di pagine ciascuna. Il primo è dedicato ad alcuni dei fiumi da lui frequentati. Queste sarebbero solo descrizioni di scarso interesse per chi non conosce i siti se non fossero fatte con una scrittura fluida e vigile, mettendo letteralmente davanti ai nostri occhi lo splendore dei paesaggi evocati.Il secondo e il terzo quarto del libro contengono i ritratti di coloro che considera "maestri" (Walton, Massas, Halford, Petit) o di alcune figure meno appariscenti ma alcune terrene. L''ultima parte del libro raccoglie aneddoti o riflessioni personali sulla mosca esatta, compagnie di pesca e altre considerazioni.L''interesse principale di questo lavoro è l''altissima qualità della sua scrittura. Purtroppo è difficile da trovare e raggiunge quote significative.');
INSERT INTO mpmc_book VALUES(29,'Pescare a ninfa. Tecniche e artificiali','Giuseppe,Re','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(30,'La filosofia della sardina','Robert,Hughes','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(31,'L'' Amo e la lenza','Mario,Albertarelli','Italiano','Storytelling','Questo libro per un appassionato è una bibbia e se si trova va assolutante acquistato e tenuto sul comodino. Non rimpiangerete i vostri soldi perché questo romanzo di pesca e di vita vissuta vi farà sognare nei ricordi più belli');
INSERT INTO mpmc_book VALUES(32,'Mouches de pêche, l''encyclopédie','Didier,Ducloux','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(33,'Della Patagonia e altri sogni. Viaggiatore con l''arte della pesca a mosca','Alvaro,Masseini','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(34,'La precisione nel lancio','Joan,Wulff','Italiano','Fishing','Joan Wulff è una delle più complete lanciatrici di tutti i tempi. Per 17 volte è stata campione nazione di lancio negli USA e recentemente è stata insignita del massimo riconoscimento della Federazione of Fly Fishers: il Lapis Lazuli. E'' insegnante di lancio da oltre 35 anni ed ha collaborato a lungo con la rivista Fly Rod & Reel');
INSERT INTO mpmc_book VALUES(35,'L''éphémère et la truite... La mouche inexacte','Pierre,Miramont','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(36,'Spinningovye primanki','A.,Chernushenko','Italiano','Products','');
INSERT INTO mpmc_book VALUES(37,'Inseguendo il sole. Appunti di viaggio dalle terre dei salmoni','Alvaro,Masseini','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(38,'Flies. Mosche da pesca','Luca,Montanari','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(39,'Trout fly recognition','John,Goddard','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(40,'Le mosche artificiali','Luciano,Tosi','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(41,'La fabbricazione delle mosche artificiali','Tony,Whieldon','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(42,'Diario di un pescatore a mosca','Roberto,Daveri','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(43,'Storia quasi vera della pesca a mosca dal Mito all’era Moderna','Agostino,Roncallo','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(44,'Macroinvertebrati dei corsi d’acqua italiani','Provincia,Trento','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(45,'Pescare a mosca','Fling,Puterbaugh','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(46,'Non solo pesca','Regione,Lombardia','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(47,'Carta ittica della Provincia di Firenze','Provincia,Firenze','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(48,'Guida delle aree protette e biodiversità sul territorio della provincia di Firenze','Provincia,Firenze','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(49,'Nell’acqua e sulle rive','Pier Luigi,Ghilarducci','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(50,'Nell’acqua e sulle rive','Pier Luigi,Ghilarducci','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(51,'Ninfe tecniche di costruzione','Giuseppe,Re','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(52,'Microchenille & C.','Mauro,Borselli','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(53,'Master Fly Tying Guide','Art,Flick’s','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(54,'Pesca con la mosca','Piero,Lumini','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(55,'I pesci d’acqua dolce','Rodolfo,Pagnini','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(56,'Trote & mosche in acque veloci','Roberto,Pragliola','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(57,'Anelli sull’Acqua','Renzo,Dionigi','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(58,'Moscas Para La Pesca','R. Pozo,Obeso','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(59,'Magie immerse','Paolo,Bertacchini','Italiano','Fly tying','Recensione da Fly Line:"É difficile definire questo libro in poche parole, ma una cosa è certa; dopo averlo letto vi rimarrà ben poco da apprendere sulle ninfe e sugli spider classici, se non cercare di costruirli con perizia e, soprattutto, di impiegarli sapientemente. Analizzerete le sommerse più efficaci e comprenderete il perché delle scelte di ogni piuma, di ogni fibra di pelo e di ogni tipologia costruttiva, ma soprattutto percorrerete il pensiero dei pescatori che hanno trasformato la pesca in passione e la passione in scienza, nell’eterno tentativo di scoprire oggi una legge e domani, forse, chissà, un pensiero del Dio che ha creato trote ed insetti.');
INSERT INTO mpmc_book VALUES(60,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(61,'Mayflies','Shane,Stalcup','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(62,'La pesca alla trota','Tony,Whieldon','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(63,'Costruirsi le mosche','Tony,Whieldon','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(64,'La pesca alla trota con la mosca','Tony,Whieldon','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(65,'La pesca con la mosca artificiale','Alfredo,Caligani','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(66,'Pesca con la mosca sommersa','Alfredo,Caligani','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(67,'Gestione della fauna ittica\nVolume I\n','Regione,Toscana','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(68,'Gestione della fauna ittica\nVolume II\n','Regione,Toscana','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(69,'Cul De Canard','Emanuele,Recchia','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(70,'Cul De Canard Fotocopie','Emanuele,Recchia','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(71,'Cul De Canard CD','Emanuele,Recchia','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(72,'Manuale tecnico di ingegneria naturalistica','Regione,Veneto','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(73,'Pesci d''Italia. Ittiofauna delle acque dolci','S.,Porcellotti','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(74,'Guida ai principali pesci presenti nelle acque lombarde','Regione,Lombardia','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(75,'Magie sull''acqua. TLT-La tecnica italiana di pesca a mosca. Ediz. illustrata','Roberto,Pragliola','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(76,'Black Bass e Ciprinidi con la mosca artificiale','Alfredo,Caligani','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(77,'Le scale di risalita per la tutela del patrimonio Ittico','Provincia,Firenze','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(78,'Indice Biotico Esteso I.B.E.','Provincia,Trento','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(79,'Come pescare a mosca','Il,Pescatore','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(80,'A pesca con la mosca artificiale','Carlo,Rancati','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(81,'Emergenti','Doug Swisher e Carl,Richards','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(82,'In mezzo scorre il fiume','Norman,McLean','Italiano','Storytelling','.');
INSERT INTO mpmc_book VALUES(83,'Il codice illustrato delle leggi sulla pesca','Tommaso Perseo e Pasquale,Buono','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(84,'Le scale di risalita per la tutela del patrimonio Ittico','Provincia,Firenze','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(85,'La tecnica dello spinning','Giandomenico,Bocchi','Italiano','Fishing','Questo libro, oltre ad essere indispensabile per chi vuole conoscere a fondo i segreti dei "cucchiaini" e delle attrezzature idonee allo spinning, è anche utile per i già iniziati, che vi troveranno molte spiegazioni per comprendere i motivi dei diversi comportamenti dei pesci nelle più svariate circostanze.');
INSERT INTO mpmc_book VALUES(86,'In mezzo al gruppo scorre il fiume','Provincia,L’Aquila','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(87,'Ephemeroidea','Marta,Grandi','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(88,'Nell’acqua e sulle rive','Pier Luigi,Ghilarducci','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(89,'L’arte della pesca con la mosca secca','Jean-Paul,Pequegnot','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(90,'Nell’acqua e sulle rive','Pier Luigi,Ghilarducci','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(91,'Le scale di risalita per la tutela del patrimonio ittico','Provincia,Firenze','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(92,'Le scale di risalita per la tutela del patrimonio ittico','Provincia,Firenze','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(93,'Venti anni al manicomio','Gianni,Gronchi','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(94,'Il fiume Bisenzio Valutazione della qualità ambientale  Aspetti biologici','Provincia,Prato','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(95,'La trota con la mosca artificiale','Alfredo,Caligani','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(96,'Pescare con la mosca','Raffaele De,Rosa','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(97,'Il pesce e la mosca','Carlo,Rancati','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(98,'Tying Flies With Cdc','Leon,Links','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(99,'Hends products','Jaromír,Karafiát','Italiano','Products','');
INSERT INTO mpmc_book VALUES(100,'Hardy’s Anglers Guide',',Hardy','Italiano','Products','');
INSERT INTO mpmc_book VALUES(101,'Magie in CDC','Agostino,Roncallo','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(102,'Dizionario delle mosche artificiali','Piero,Lumini','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(103,'Il pescatore con la mosca','Roberto,Pragliola','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(104,'Manuale del moderno costruttore di mosche artificiali','Fabio,Federighi','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(105,'La trota e la mosca','Brian,Clarke','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(106,'Nuove tecniche di costruzione. Metodi e materiali moderni','Oliver,Edwards','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(107,'Torrenti & Dry Fly','Massimo,Magliocco','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(108,'Century End','Paul,Ptalis','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(109,'The Fly Tyers Nymph Manual','Randall,Kaufmann','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(110,'Quando le trote diventano smaliziate','Doug,Swisher','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(111,'I dressings di Fly Line Mosche artificiali, cloni e mutanti','Roberto,Messori','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(112,'Enciclopedia della pesca a mosca','Charles,Jardine','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(113,'Appese ad un filo','Paolo,Germani','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(114,'Appese ad un filo','Paolo,Germani','Italiano','Fly tying','');
INSERT INTO mpmc_book VALUES(115,'Gli insetti di Fly Line','Roberto,Messori','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(116,'Il libro completo della pesca a mosca','Strenua,Ulnitz','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(117,'500 Fly Dressings',',Veniard','Italiano','Products','');
INSERT INTO mpmc_book VALUES(118,'Fly storie e riflessioni sulla pesca a mosca','Marco,Cipriani','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(119,'Fly Line Ecosistemi Fluviali Raccolta anno 2000','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(120,'Fly Line Ecosistemi Fluviali Raccolta anno 2009','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(121,'Fly Line Ecosistemi Fluviali Raccolta anno 1998','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(122,'Fly Line Ecosistemi Fluviali Raccolta anno 2006','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(123,'Fly Line Ecosistemi Fluviali Raccolta anno 1996','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(124,'Fly Line Ecosistemi Fluviali Raccolta anno 1997','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(125,'Fly Line Ecosistemi Fluviali Raccolta anno 2007','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(126,'Fly Line Ecosistemi Fluviali Raccolta anno 2005','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(127,'Fly Line Ecosistemi Fluviali Raccolta anno 2003','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(128,'Fly Line Ecosistemi Fluviali Raccolta anno 2004','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(129,'Fly Line Ecosistemi Fluviali Raccolta anno 2008','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(130,'Fly Line Ecosistemi Fluviali Raccolta anno 2001','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(131,'Fly Line Ecosistemi Fluviali Raccolta anno 1995','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(132,'Fly Line Ecosistemi Fluviali Raccolta anno 2002','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(133,'Fly Line Ecosistemi Fluviali Raccolta anno 1999','Roberto,Messori','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(134,'Gli insetti di Fly Line','Roberto,Messori','Italiano','Entomology','');
INSERT INTO mpmc_book VALUES(135,'Il pescatore perfetto','Izaak,Walton','Italiano','Travel','');
INSERT INTO mpmc_book VALUES(136,'Mouche Noyee','Louisiana,Carrere','Italiano','Fishing','');
INSERT INTO mpmc_book VALUES(137,'La pesca del temolo con la mosca','J. d’Or,Sinclair','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(138,'Riabilitazione della mosca sommersa','Léonce de,Boisset','Italiano','Storytelling','Il libro si compone di tre parti principali, si tratta infatti di riflessioni su attrezzature, tecniche e condizioni di pesca (tempo, livello dell''acqua, ecc.).Nessuna affermazione tecnica scoraggiante, piuttosto una serie di riflessioni e un appello all''utilizzo della mosca sommersa. Ognuno può, secondo il suo gusto e secondo le circostanze, usare la mosca secca o sommersa. Entrambi i metodi hanno il loro posto, il loro fascino, i loro successi e le loro difficoltà');
INSERT INTO mpmc_book VALUES(139,'Scritto di sera','Léonce de,Boisset','Italiano','Storytelling','Sottotitolato "Le chiacchiere di un vecchio pescatore di trote", quest''opera offre al lettore il sottile piacere di una scrittura straordinaria.È suddiviso in quattro parti di una cinquantina di pagine ciascuna. Il primo è dedicato ad alcuni dei fiumi da lui frequentati. Queste sarebbero solo descrizioni di scarso interesse per chi non conosce i siti se non fossero fatte con una scrittura fluida e vigile, mettendo letteralmente davanti ai nostri occhi lo splendore dei paesaggi evocati.Il secondo e il terzo quarto del libro contengono i ritratti di coloro che considera "maestri" (Walton, Massas, Halford, Petit) o di alcune figure meno appariscenti ma alcune terrene. L''ultima parte del libro raccoglie aneddoti o riflessioni personali sulla mosca esatta, compagnie di pesca e altre considerazioni.L''interesse principale di questo lavoro è l''altissima qualità della sua scrittura. Purtroppo è difficile da trovare e raggiunge quote significative.');
INSERT INTO mpmc_book VALUES(140,'Pris sur le vif Una vita sulla pesca','Charles,Ritz','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(141,'Il temolo pesce sportivo','Léonce de,Boisset','Italiano','Storytelling','A dispetto dell''età. Il temolo, pesce sportivo é in grado di offrire tutta la freschezza e l''attualità tipiche di un'' opera senza tempo. Per la maggior parte dei "vecchi" moscaioli, L''Ombre, poisson de sport rappresenta un tuffo nel passato, un ritorno alla giovinezza e ai fasti alieutici di un periodo d'' oro e apprezzeranno sicuramente l'' idea di divulgarne l''edizione italiana. Per i più giovani, l''opera di de Boisset rappresenta invece la conferma che la pesca a mosca non ha età e in queste pagine troveranno consigli e nozioni ancora attuali e di cui farne tesoro , che solo l''esperienza e una grandissima passione possono far acquisire. Il tutto presentato con uno stile semplice e scorrevole che ne rende oltremodo piacevole la lettura e ne fa apprezzare i contenuti');
INSERT INTO mpmc_book VALUES(142,'Fly Fishing  Pesca a mosca. 9-2006','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(143,'Fly Fishing  Pesca a mosca. 6-2005','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(144,'Fly Fishing  Pesca a mosca. 0-2004','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(145,'Fly Fishing  Pesca a mosca. 1-2004','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(146,'Fly Fishing  Pesca a mosca. 10-2006','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(147,'Fly Fishing  Pesca a mosca. 7-2005','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(148,'Fly Fishing  Pesca a mosca. 5-2005','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(149,'Fly Fishing  Pesca a mosca. 4-2005','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(150,'Fly Fishing  Pesca a mosca. 8-2005','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(151,'Fly Fishing  Pesca a mosca. 2-2004','Marco,Bozzano','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(152,'I pesci','Marcus,Elieser Bloch','Italiano','Storytelling','');
INSERT INTO mpmc_book VALUES(153,'HO2 Magazine  2-2008','Giovanni,Cecconi','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(154,'HO2 Magazine  3-2009','Giovanni,Cecconi','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(155,'HO2 Magazine  4-2008','Giovanni,Cecconi','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(156,'HO2 Magazine  3-2009','Giovanni,Cecconi','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(157,'HO2 Magazine  1-2008','Giovanni,Cecconi','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(158,'HO2 Magazine  3-2008','Giovanni,Cecconi','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(159,'Speciale Mosca  2-1994','Carlo,Galigani','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(160,'Speciale Mosca  3-1995','Carlo,Galigani','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(161,'Speciale Mosca  2-1996','Carlo,Galigani','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(162,'Mosca & Spinning anno III  1992-6','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(163,'Mosca & Spinning anno III  1992-7','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(164,'Mosca & Spinning anno III  1992-4','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(165,'Mosca & Spinning anno III  1992-8','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(166,'Mosca & Spinning anno IV  1993-7','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(171,'Mosca & Spinning anno IV  1993-8','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(172,'Mosca & Spinning anno IV  1993-1','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(173,'Mosca & Spinning anno IV  1993-4','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(174,'Mosca & Spinning anno IV  1993-9','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(175,'Mosca & Spinning anno V 1994-2','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(176,'Mosca & Spinning anno V 1994-1','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(177,'Mosca & Spinning 1995-4','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(178,'Mosca & Spinning anno V 1994-5','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(179,'Mosca & Spinning anno V 1994-6','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(180,'Mosca & Spinning anno V 1994-5','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(181,'Mosca & Spinning anno V 1994-12','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(182,'Mosca & Spinning anno V 1994-4','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(183,'Mosca & Spinning anno V 1994-4','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(184,'Mosca & Spinning 1995-9','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(185,'Mosca & Spinning 1995-1','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(186,'Mosca & Spinning 1995-10','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(187,'Mosca & Spinning 1995-12','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(188,'Mosca & Spinning 1995-2','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(189,'Mosca & Spinning 1995-6','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(190,'Mosca & Spinning 1995-11','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(191,'Mosca & Spinning 1995-7-8','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(192,'Mosca & Spinning 1995-3','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(193,'Mosca & Spinning 1995-5','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(194,'Mosca & Spinning anno V 1994-6','Eugenio,Cecioni','Italiano','Magazine','');
INSERT INTO mpmc_book VALUES(195,'Fly Line Ecosistemi Fluviali Speciale Storia','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line sulla storia della pesca a mosca');
INSERT INTO mpmc_book VALUES(196,'Fly Line Ecosistemi Fluviali Speciale Attrezzature 2003','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Attrezzature anno 2003');
INSERT INTO mpmc_book VALUES(197,'Fly Line Ecosistemi Fluviali Speciale Attrezzature 2002','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Attrezzature anno 2002');
INSERT INTO mpmc_book VALUES(198,'Fly Line Ecosistemi Fluviali Speciale Attrezzature 2001','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Attrezzature anno 2001');
INSERT INTO mpmc_book VALUES(199,'Fly Line Ecosistemi Fluviali Speciale Itinerari  2002','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Itinerari anno 2002');
INSERT INTO mpmc_book VALUES(200,'Fly Line Ecosistemi Fluviali Speciale Itinerari  2004','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Itinerari anno 2004');
INSERT INTO mpmc_book VALUES(201,'Fly Line Ecosistemi Fluviali Speciale Itinerari  2007','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Itinerari anno 2007');
INSERT INTO mpmc_book VALUES(202,'Fly Line Ecosistemi Fluviali Speciale Itinerari  2003','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Itinerari anno 2003');
INSERT INTO mpmc_book VALUES(203,'Fly Line Ecosistemi Fluviali Speciale Itinerari  2005','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Itinerari anno 2005');
INSERT INTO mpmc_book VALUES(204,'Fly Line Ecosistemi Fluviali Speciale Itinerari  2006','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Itinerari anno 2006');
INSERT INTO mpmc_book VALUES(205,'Fly Line Ecosistemi Fluviali Speciale Dressing 2006','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2006');
INSERT INTO mpmc_book VALUES(206,'Fly Line Ecosistemi Fluviali Speciale Dressing 2007','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2007');
INSERT INTO mpmc_book VALUES(207,'Fly Line Ecosistemi Fluviali Speciale Dressing 2007','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2007');
INSERT INTO mpmc_book VALUES(208,'Fly Line Ecosistemi Fluviali Speciale Dressing 2003','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2003');
INSERT INTO mpmc_book VALUES(209,'Fly Line Ecosistemi Fluviali Speciale Dressing 2001','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2001');
INSERT INTO mpmc_book VALUES(210,'Fly Line Ecosistemi Fluviali Speciale Dressing 2002','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2002');
INSERT INTO mpmc_book VALUES(211,'Fly Line Ecosistemi Fluviali Speciale Dressing 2005','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2005');
INSERT INTO mpmc_book VALUES(212,'Fly Line Ecosistemi Fluviali Speciale Dressing 2004','Roberto,Messori','Italiano','Magazine','Speciale rivista Fly Line Dressing anno 2004');
INSERT INTO mpmc_book VALUES(213,'Fly Line Ecosistemi Fluviali Raccolta anno 2011','Roberto,Messori','Italiano','Magazine','Raccolta riviste Fly Line anno 2011');
INSERT INTO mpmc_book VALUES(214,'Fly Line Ecosistemi Fluviali Raccolta anno 2010','Roberto,Messori','Italiano','Magazine','Raccolta riviste Fly Line anno 2010');
INSERT INTO mpmc_book VALUES(215,'Pescare a mosca','Fling,Puterbaugh','Italiano','Fishing','Modelli selezionati e tecniche di lancio degli artificiali');
INSERT INTO mpmc_book VALUES(216,'Le mosche artificiali','Luciano,Tosi','Italiano','Fly tying','Nozioni di entomologia e tecniche di costruzione');
INSERT INTO mpmc_book VALUES(217,'Come pescare a mosca','Il,Pescatore','Italiano','Fishing','Attrezzature e tecniche base');
INSERT INTO mpmc_book VALUES(218,'Come pescare a mosca','Il,Pescatore','Italiano','Fly tying','Costruzione di artificiali');
INSERT INTO mpmc_book VALUES(219,'Tecniche di pesca in acque dolci','M,Todescato','Italiano','Fishing','Tecniche di pesca in acque dolci');
INSERT INTO mpmc_book VALUES(220,'Pesca in acque dolci','Jean,Goubert','Italiano','Fishing','Pesca in acque dolci');
CREATE TABLE "mpmc_storico_bak"(
  id INT not null primary key,
  title TEXT,
  author TEXT,
  username TEXT,
  status TEXT,
  borrowed DATE,
  due_back DATE
);
INSERT INTO mpmc_storico_bak VALUES(1,'Mouche Noyee','Louisiana,Carrere','andrea.nardi','a','2020-10-14','2021-05-26');
INSERT INTO mpmc_storico_bak VALUES(2,'Il temolo pesce sportivo','Léonce de,Boisset','giuliano.terzuoli','a','2020-10-14','2020-10-21');
INSERT INTO mpmc_storico_bak VALUES(3,'Il pescatore con la mosca','Roberto,Pragliola','alessio.stiaccini','a','2020-10-14','2020-10-28');
INSERT INTO mpmc_storico_bak VALUES(4,'Scritto di sera','Léonce de,Boisset','giuliano.terzuoli','a','2020-10-21','2021-05-26');
INSERT INTO mpmc_storico_bak VALUES(5,'Gli insetti di Fly Line','Roberto,Messori','andrea.nardi','o','2024-03-13','9999-01-01');
INSERT INTO mpmc_storico_bak VALUES(6,'Trout fly recognition','John,Goddard','bruno.calieri','a','2021-05-26','2021-06-09');
INSERT INTO mpmc_storico_bak VALUES(7,'Pesca a mosca. Tecniche di lancio e pesca con la mosca artificiale. Pesci, attrezzatura','Luciano,Tosi','piero.dibella','a','2021-01-21','2021-01-21');
INSERT INTO mpmc_storico_bak VALUES(8,'Anelli sull’Acqua','Renzo,Dionigi','andrea.nardi','a','2021-05-26','2021-06-09');
INSERT INTO mpmc_storico_bak VALUES(9,'La roccia condivisa','Mauro,Raspini','giuliano.terzuoli','a','2021-05-26','2021-06-09');
INSERT INTO mpmc_storico_bak VALUES(10,'La pesca del temolo con la mosca','J. d’Or,Sinclair','andrea.nardi','a','2021-09-15','2021-09-29');
INSERT INTO mpmc_storico_bak VALUES(11,'Nell’acqua e sulle rive','Pier Luigi,Ghilarducci','andrea.nardi','a','2021-09-22','2021-09-22');
INSERT INTO mpmc_storico_bak VALUES(12,'In mezzo scorre il fiume','Norman,McLean','andrea.nardi','a','2021-09-30','2021-11-10');
INSERT INTO mpmc_storico_bak VALUES(13,'Inseguendo il sole. Appunti di viaggio dalle terre dei salmoni','Alvaro,Masseini','giuliano.terzuoli','a','2021-10-06','2022-02-23');
INSERT INTO mpmc_storico_bak VALUES(14,'Pescare a ninfa. Tecniche e artificiali','Giuseppe,Re','andrea.lotti','a','2021-10-06','2023-06-12');
INSERT INTO mpmc_storico_bak VALUES(15,'Pris sur le vif Una vita sulla pesca','Charles,Ritz','alessio.stiaccini','a','2021-10-06','2023-06-12');
INSERT INTO mpmc_storico_bak VALUES(16,'Ephemeroidea','Marta,Grandi','andrea.nardi','a','2021-11-10','2021-12-08');
INSERT INTO mpmc_storico_bak VALUES(17,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','alessandro.bartolini','o','2024-03-13','9999-01-01');
INSERT INTO mpmc_storico_bak VALUES(18,'Magie in CDC','Agostino,Roncallo','giuliano.terzuoli','a','2022-02-23','2022-12-01');
INSERT INTO mpmc_storico_bak VALUES(19,'Magie sull''acqua. TLT-La tecnica italiana di pesca a mosca. Ediz. illustrata','Roberto,Pragliola','simone.burgassi','a','2023-01-25','2023-02-25');
INSERT INTO mpmc_storico_bak VALUES(20,'Moscas Para La Pesca','R. Pozo,Obeso','bruno.calieri','r','2023-02-22','2023-02-22');
INSERT INTO mpmc_storico_bak VALUES(21,'La trota con la mosca artificiale','Alfredo,Caligani','alessandro.bartolini','o','2023-02-22','9999-01-01');
INSERT INTO mpmc_storico_bak VALUES(22,'Magie sull''acqua. TLT-La tecnica italiana di pesca a mosca. Ediz. illustrata','Roberto,Pragliola','simone.montecchi','a','2023-01-25','2023-11-22');
INSERT INTO mpmc_storico_bak VALUES(23,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','andrea.nardi','a','2023-10-04','2023-11-22');
INSERT INTO mpmc_storico_bak VALUES(24,'Microchenille & C.','Mauro,Borselli','andrea.nardi','a','2023-11-22','2024-01-24');
INSERT INTO mpmc_storico_bak VALUES(25,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','giuliano.terzuoli','a','2023-12-20','2024-03-13');
INSERT INTO mpmc_storico_bak VALUES(26,'Manuale del moderno costruttore di mosche artificiali','Fabio,Federighi','alessandro.bartolini','o','2024-02-14','9999-01-01');
INSERT INTO mpmc_storico_bak VALUES(27,'Enciclopedia della pesca a mosca','Charles,Jardine','simone.burgassi','a','2024-02-28','2024-03-06');
INSERT INTO mpmc_storico_bak VALUES(28,'Gli insetti di Fly Line','Roberto,Messori','simone.burgassi','a','2024-03-13','2024-04-24');
INSERT INTO mpmc_storico_bak VALUES(29,'Magie immerse','Paolo,Bertacchini','giuliano.terzuoli','o','2024-03-13','9999-01-01');
CREATE TABLE "mpmc_user" (
"id" serial NOT NULL PRIMARY KEY, 
"first_name" varchar(150) NOT NULL,
"last_name" varchar(150) NOT NULL, 
"username" varchar(150) NOT NULL UNIQUE, 
"password" varchar(128), 
"email" varchar(254), 
"last_login" DATE NULL, 
"date_joined" DATE, 
"is_superuser" bool, 
"is_staff" bool, 
"is_active" bool
);
INSERT INTO mpmc_user VALUES(1,'admin','admin','admin',NULL,'info@ilmartinpescatore.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(2,'Andrea','Nardi','andrea.nardi',NULL,'andrea.nardi.mail@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(4,'Giuliano','Terzuoli','giuliano.terzuoli',NULL,'giuliano.terzuoli@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(5,'Alessio','Stiaccini','alessio.stiaccini',NULL,'alessio.stiaccini@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(6,'Andrea','Lotti','andrea.lotti',NULL,'lottino7@hotmail.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(7,'Bruno','Calieri','bruno.calieri',NULL,'b.calieri@tin.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(8,'Marco','Del Sorbo','marco.delsorbo',NULL,'delsorbomarco60@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(9,'Piero','Caini','piero.caini',NULL,'cainefaf@pierocaini.191.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(10,'Emiliano','Lippi','emiliano.lippi',NULL,'e.lippi78@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(11,'Manrico','Milli','manrico.milli',NULL,'manricomilli@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(12,'Roberto','Mordoni','roberto.mordoni',NULL,'roberto.mordoni@virgilio.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(13,'Simone','Burgassi','simone.burgassi',NULL,'simone.burgassi@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(14,'Piero','Risaliti','piero.risaliti',NULL,'piero.risaliti@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(15,'Piero','Di Bella','piero.dibella',NULL,'lupolupo66@libero.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(16,'Simone','Montecchi','simone.montecchi',NULL,'m.simone67@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(17,'Alessandro','Bartolini','alessandro.bartolini',NULL,'alexbartolini2012@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(18,'Marco','Niccolini','marco.niccolini',NULL,'marco.niccolini83@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(19,'Leonardo','Scommegna','leonardo.scommegna',NULL,'leo94sc@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(20,'Jody','Mattioli','jody.mattioli',NULL,'jodymattioli@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(21,'Andrea','Giani','andrea.giani',NULL,'a_giani@libero.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(22,'Patrizio','Rinaldi','patrizio.rinaldi',NULL,'patririnaldi5@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(23,'Vittorio','Moreni','vittorio.moreni',NULL,'vittorio@delcroixmoreni.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(24,'Filippo','Fusi','filippo.fusi',NULL,'pippofusi77@yahoo.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(25,'Silvio','Marsicano','silvio.marsicano',NULL,'silvio.marsicano@tin.it',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(26,'Andrea','Navarria','andrea.navarria',NULL,'andreanavarria@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(27,'Luca','Mordoni','luca.mordoni',NULL,'',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(28,'Filippo','Daddi','filippo.daddi',NULL,'filippodaddi71@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(29,'Luca','Guasti','luca.guasti',NULL,'',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(30,'Tiberio','Piazzini','tiberio.piazzini',NULL,'tibepiazzi@gmail.com',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mpmc_user VALUES(31,'Alessandro','Torrini','alessandro.torrini',NULL,'a.torrini69@gmail.com',NULL,NULL,NULL,NULL,NULL);
CREATE TABLE mpmc_storico (
	id INTEGER NOT NULL, 
	title VARCHAR(100), 
	author VARCHAR(100), 
	username VARCHAR(100), 
	status VARCHAR(1), 
	borrowed DATE, 
	due_back DATE, 
	PRIMARY KEY (id)
);
INSERT INTO mpmc_storico VALUES(1,'Mouche Noyee','Louisiana,Carrere','andrea.nardi','a','2020-10-14','2021-05-26');
INSERT INTO mpmc_storico VALUES(2,'Il temolo pesce sportivo','Léonce de,Boisset','giuliano.terzuoli','a','2020-10-14','2020-10-21');
INSERT INTO mpmc_storico VALUES(3,'Il pescatore con la mosca','Roberto,Pragliola','alessio.stiaccini','a','2020-10-14','2020-10-28');
INSERT INTO mpmc_storico VALUES(4,'Scritto di sera','Léonce de,Boisset','giuliano.terzuoli','a','2020-10-21','2021-05-26');
INSERT INTO mpmc_storico VALUES(5,'Gli insetti di Fly Line','Roberto,Messori','andrea.nardi','o','2024-03-13','9999-01-01');
INSERT INTO mpmc_storico VALUES(6,'Trout fly recognition','John,Goddard','bruno.calieri','a','2021-05-26','2021-06-09');
INSERT INTO mpmc_storico VALUES(7,'Pesca a mosca. Tecniche di lancio e pesca con la mosca artificiale. Pesci, attrezzatura','Luciano,Tosi','piero.dibella','a','2021-01-21','2021-01-21');
INSERT INTO mpmc_storico VALUES(8,'Anelli sull’Acqua','Renzo,Dionigi','andrea.nardi','a','2021-05-26','2021-06-09');
INSERT INTO mpmc_storico VALUES(9,'La roccia condivisa','Mauro,Raspini','giuliano.terzuoli','a','2021-05-26','2021-06-09');
INSERT INTO mpmc_storico VALUES(10,'La pesca del temolo con la mosca','J. d’Or,Sinclair','andrea.nardi','a','2021-09-15','2021-09-29');
INSERT INTO mpmc_storico VALUES(11,'Nell’acqua e sulle rive','Pier Luigi,Ghilarducci','andrea.nardi','a','2021-09-22','2021-09-22');
INSERT INTO mpmc_storico VALUES(12,'In mezzo scorre il fiume','Norman,McLean','andrea.nardi','a','2021-09-30','2021-11-10');
INSERT INTO mpmc_storico VALUES(13,'Inseguendo il sole. Appunti di viaggio dalle terre dei salmoni','Alvaro,Masseini','giuliano.terzuoli','a','2021-10-06','2022-02-23');
INSERT INTO mpmc_storico VALUES(14,'Pescare a ninfa. Tecniche e artificiali','Giuseppe,Re','andrea.lotti','a','2021-10-06','2023-06-12');
INSERT INTO mpmc_storico VALUES(15,'Pris sur le vif Una vita sulla pesca','Charles,Ritz','alessio.stiaccini','a','2021-10-06','2023-06-12');
INSERT INTO mpmc_storico VALUES(16,'Ephemeroidea','Marta,Grandi','andrea.nardi','a','2021-11-10','2021-12-08');
INSERT INTO mpmc_storico VALUES(17,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','alessandro.bartolini','o','2024-03-13','9999-01-01');
INSERT INTO mpmc_storico VALUES(18,'Magie in CDC','Agostino,Roncallo','giuliano.terzuoli','a','2022-02-23','2022-12-01');
INSERT INTO mpmc_storico VALUES(19,'Magie sull''acqua. TLT-La tecnica italiana di pesca a mosca. Ediz. illustrata','Roberto,Pragliola','simone.burgassi','a','2023-01-25','2023-02-25');
INSERT INTO mpmc_storico VALUES(20,'Moscas Para La Pesca','R. Pozo,Obeso','bruno.calieri','r','2023-02-22','2023-02-22');
INSERT INTO mpmc_storico VALUES(21,'La trota con la mosca artificiale','Alfredo,Caligani','alessandro.bartolini','o','2023-02-22','9999-01-01');
INSERT INTO mpmc_storico VALUES(22,'Magie sull''acqua. TLT-La tecnica italiana di pesca a mosca. Ediz. illustrata','Roberto,Pragliola','simone.montecchi','a','2023-01-25','2023-11-22');
INSERT INTO mpmc_storico VALUES(23,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','andrea.nardi','a','2023-10-04','2023-11-22');
INSERT INTO mpmc_storico VALUES(24,'Microchenille & C.','Mauro,Borselli','andrea.nardi','a','2023-11-22','2024-01-24');
INSERT INTO mpmc_storico VALUES(25,'Probabili illusioni. Le mosche artificiali di Renato Cellere','Roberto,Messori','giuliano.terzuoli','a','2023-12-20','2024-03-13');
INSERT INTO mpmc_storico VALUES(26,'Manuale del moderno costruttore di mosche artificiali','Fabio,Federighi','alessandro.bartolini','o','2024-02-14','9999-01-01');
INSERT INTO mpmc_storico VALUES(27,'Enciclopedia della pesca a mosca','Charles,Jardine','simone.burgassi','a','2024-02-28','2024-03-06');
INSERT INTO mpmc_storico VALUES(28,'Gli insetti di Fly Line','Roberto,Messori','simone.burgassi','a','2024-03-13','2024-04-24');
INSERT INTO mpmc_storico VALUES(29,'Magie immerse','Paolo,Bertacchini','giuliano.terzuoli','o','2024-03-13','9999-01-01');
CREATE INDEX mpmc_book_auth on mpmc_book(author);
CREATE INDEX ix_mpmc_storico_id ON mpmc_storico (id);
COMMIT;
